language: php

dist: trusty
sudo: required

services:
  - memcached
  - mysql
  - postgresql
  - redis-server

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3 # Fix error with PostGIS extension not being found when `CREATE EXTENSION` is issued.

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

jobs:
  fast_finish: true

  include:
    # Minimal tests set: SQLite on PHP 5.6/7.0/7.1/HHVM, MySQL and PostgreSQL on PHP 7.1, code sniffer.
    - stage: minimal
      php: 5.6
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.0
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: minimal
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.6 DB_POSTGIS=1 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: minimal
      php: hhvm
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql'"
    - stage: minimal
      php: 7.1
      services: []
      addons: {}
      env: "RUN=phpcs"
      before_script: skip
      script: |
        vendor/bin/phpcs -n -p --extensions=php \
          --standard=vendor/cakephp/cakephp-codesniffer/CakePHP --ignore=/Migrations/,/Seeds/ \
          ./config ./src ./tests ./plugins/*/*/config ./plugins/*/*/src ./plugins/*/*/tests
      after_success: skip

    # Complete tests suite: SQLite on PHP 5.6 with lowest dependencies, MySQL and PostgreSQL on PHP 5.6/7.0,
    #   MySQL 5.6 and PostgreSQL 9.5 on PHP 7.1, MySQL on HHVM, static code analyzer.
    - stage: complete
      php: 5.6
      env: "DB=sqlite db_dsn='sqlite:///tmp/test.sql' PREFER_LOWEST=1"
      install: composer update --prefer-dist --prefer-lowest --no-interaction
    - stage: complete
      php: 5.6
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 5.6
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.0
      env: "DB=pgsql DB_VERSION=9.6 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
    - stage: complete
      php: 7.1
      env: "DB=mysql DB_VERSION=5.6 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.1
      env: "DB=pgsql DB_VERSION=9.5 db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
      addons:
        postgresql: "9.5"
    - stage: complete
      php: hhvm
      env: "DB=mysql DB_VERSION=5.7 db_dsn='mysql://root@localhost/bedita_test'"
    - stage: complete
      php: 7.1
      services: []
      addons: {}
      env: "RUN=phpstan"
      install:
        - composer install --prefer-dist --no-interaction
        - composer require --dev phpstan/phpstan
      before_script: skip
      script: vendor/bin/phpstan analyse --no-progress src plugins/BEdita/API/src plugins/BEdita/Core/src
      after_success: skip

    # Deployment on Heroku demo app.
    - stage: deploy
      php: 7.1
      services: []
      addons: {}
      branches: # Hopefully this will work someday.
        only:
          - 4-cactus
      before_script: skip
      script: skip
      after_success: skip
      deploy:
        provider: heroku
        app: bedita4
        skip_cleanup: true
        run:
          - "bin/cake migrations migrate -p BEdita/Core"
          - "bin/cake cache clear_all"
        api_key:
          secure: IoV+GK7hyX8/uWmuF7xuc+4SM0a9mCmKAckOTJ+LZj1zpzXRE8LkPXm5GnuYoO/ambRoZkORDwclrXMsloY3TJMFvJxG6UnOlKANBzwKankZK6vWv0O3Jni4TtbW48OShH7yj6iCS7uvwPFrA76c21qlLBp34QAFJO0y73lS+sY=
        on:
          repo: bedita/bedita # Play nicely on forks.
          branch:
            - 4-cactus

  allow_failures:
    - env: "RUN=phpstan"

before_install:
  # Use GitHub OAuth token with Composer to increase API limits.
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi

install:
  # Install Composer dependencies.
  - composer install --prefer-dist --no-interaction
  - if [ "$TRAVIS_PHP_VERSION" = 'hhvm' ]; then composer require lorenzo/multiple-iterator=~1.0; fi

before_script:
  # Enable required PHP Extensions.
  - |
    if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then
      echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi
  - phpenv rehash
  - set +H

  # Set up and configure databases.
  - | # Install MySQL 5.7.
    if [ "$DB" = 'mysql' ] && [ "$DB_VERSION" = '5.7' ]; then
      echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
      wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
      sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
      sudo apt-get update -q
      sudo apt-get install -q -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" mysql-server
      sudo mysql_upgrade
    fi
  - if [ "$DB" = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE bedita_test;'; mysql -u root -e 'SHOW DATABASES;'; fi
  - if [ "$DB" = 'pgsql' ]; then psql -c 'CREATE DATABASE bedita_test;' -U postgres; fi
  - if [ "$DB" = 'pgsql' ] && [ "$DB_POSTGIS" = '1' ]; then psql -c 'CREATE EXTENSION postgis;' -U postgres; fi

script: vendor/bin/phpunit --coverage-clover=clover.xml # Run PHPUnit.

after_success: bash <(curl -s https://codecov.io/bash) # Upload test coverage reports to CodeCov.

notifications:
  email: false
  slack:
    secure: TJ1c35YLgdYmIQRB58RKuEPDBN1XZYBjFI842lxa5Rl6FW/x+cJIYNCK3mU48/ULw9RfUla3bLf/oyffaj6pATRSK/jshiVKDU2Pq6yd/YV1aXpaMQLpzr8UJZk/KrG5cDAXhHW0U8O95sVpZm/pLwkNtk5tMPiuvJ35oVJyNuM=
