language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

services:
  - memcached
  - redis-server

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - "DB=sqlite db_dsn='sqlite:///:memory:'"
    - "DB=mysql db_dsn='mysql://travis@0.0.0.0/bedita_test'"
    - "DB=pgsql db_dsn='postgres://postgres@127.0.0.1/bedita_test'"
  global:
    - RUN_TESTS=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: RUN_CS=1 RUN_TESTS=0

  exclude:
    - php: hhvm
      env: "DB=pgsql db_dsn='postgres://postgres@127.0.0.1/bedita_test'"

  allow_failures:
    - php: hhvm

before_script:
  - echo "$TRAVIS_PHP_VERSION"
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --prefer-dist --no-interaction

  - if [ "$DB" = 'mysql' ]; then mysql -e 'CREATE DATABASE bedita_test;'; fi
  - if [ "$DB" = 'pgsql' ]; then psql -c 'CREATE DATABASE bedita_test;' -U postgres; fi

  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" != 'hhvm' ]; then echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" = 'hhvm' ]; then composer require lorenzo/multiple-iterator=~1.0; fi

  - phpenv rehash
  - set +H

script:
  - if [ "$RUN_TESTS" = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [ "$RUN_CS" = '1' ]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./plugins/*/*/src ./plugins/*/*/tests; fi

after_success:
  - if [ "$RUN_TESTS" = '1' ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
